---
- name: Stop and disable Fluent Bit service (RHEL 8)
  ansible.builtin.command: systemctl disable --now fluent-bit
  ignore_errors: true

- name: Remove Fluent Bit package (RHEL 8)
  ansible.builtin.command: dnf -y remove {{ pkg_rhel_fluent_bit | join(' ') }}
  register: fluent_bit_remove
  changed_when: "'Nothing to do.' not in fluent_bit_remove.stdout"
  ignore_errors: true

- name: Remove Fluent Bit configuration and data
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/fluent-bit
    - /var/lib/fluent-bit
    - /opt/fluent-bit
  ignore_errors: true

- name: Remove audit packages (RHEL 8)
  ansible.builtin.command: dnf -y remove {{ pkg_rhel_log_forwarder_audit | join(' ') }}
  register: audit_remove
  changed_when: "'Nothing to do.' not in audit_remove.stdout"
  ignore_errors: true
  when:
    - log_forwarder_audit_enabled | bool
    - log_forwarder_audit_remove | bool

- name: Remove audit rules
  ansible.builtin.file:
    path: "{{ log_forwarder_audit_rules_file }}"
    state: absent
  ignore_errors: true
  notify: reload audit rules

- name: Remove Fluent Bit repository (RHEL 8)
  ansible.builtin.command: rm -f /etc/yum.repos.d/fluent-bit.repo
  args:
    removes: /etc/yum.repos.d/fluent-bit.repo
  ignore_errors: true
  when: log_forwarder_remove_repo | bool
...