---
# Windows/20_configure.yml - deploy configuration and restart on changes

- name: Deploy winlogbeat.yml
  ansible.windows.win_template:
    src: winlogbeat.yml.j2
    dest: '{{ winlogbeat_config }}'
  notify: restart winlogbeat
...
